### ISSUE TITLE
AutoDisconnecter stores refrence to functor object instead of object itself

### ISSUE THREAD

**Issue by yuriy228** [misje/once#3]
Hi! First of all thanks for your small helper. I was also surprised that this functionality has still not included in QT.
The problem is that the member AutoDisconnecter::func is treated as a reference and therefore it saves a reference to the functor object which is not saved elsewhere.
No idea why. You use "Func &&func" so Func should be deduced to the type itself. 
It can be easily verified by static_assert( !std::is_reference< decltype( func ) >::value , ""), which won't compile.
The solution can be replacing the member with 
std::remove_reference_t< Func > func;
Plus you need to remove const from operator () and call() as they call not-const callable of its member.

**Comment by yuriy228** [comment]
Besides, I tested in gcc 6.5 and MinGW 7.3, c++14

**Comment by misje** [comment]
Thanks for taking the time to write this. I actually had `remove_reference()` in my initial version, but I never saw the need for it in the code I used this for and the code I wrote to test it with. Hence I removed it. I'll add it back.

Out of curiosity, do you have a block of code that triggers this compilation issue?

**Comment by yuriy228** [comment]
The reproducing code is very simple. It might be something like this:

    auto obj = new QObject();

    {
      QString str = "str";
      struct Item {
          int v = 123;
          ~Item() { v = 0; }
      } item;

      auto func = [str, item]() {
          assert( item.v == 123 );      // a low-level memory check; here we get an alert 
          assert( str == "str" );       // here we can get an allert or a crash depending on the luck as the object doen't exist
      };

      Once::connect( obj, &QObject::destroyed, func );
    }

    delete obj;

**Comment by misje** [comment]
I implemented your suggestions. Thanks for pointing out the issues, and even more so for providing reproducible test code!
